_extends: github-apps-config-next
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: false
      required_status_checks:
        strict: false
        contexts:
          - 'ci/circleci: test'
          - build-test
          - 'ci/circleci: build'
      enforce_admins: true
      restrictions:
        users: []
        teams: []
