version: 2.1

orbs:
  node: circleci/node@4.6.0
  browser-tools: circleci/browser-tools@1.2.3

references:

  #
  # Workspace
  #
  container_config_node:
    &container_config_node
    working_directory: ~/project/build
    docker:
      - image: cimg/node:<< parameters.node-version >>-browsers
    parameters:
      node-version:
        default: "16.14"
        type: string

  workspace_root: &workspace_root ~/project

  attach_workspace:
    &attach_workspace
    attach_workspace:
      at: *workspace_root

  # Cache creation
  #
  create_cache:
    &create_cache
    save_cache:
      key: cache-v1-{{ .Branch }}-{{ checksum "./package.json" }}
      paths:
        - ./node_modules/

  # Cache restoration
  #
  restore_cache:
    &restore_cache
    restore_cache:
      keys:
        - cache-v1-{{ .Branch }}-{{ checksum "./package.json" }}

  # Filters
  #
  filters_only_main:
    &filters_only_main
    branches:
      only:
        - main

  filters_only_renovate_nori:
    &filters_only_renovate_nori
    branches:
      only: /(^renovate-.*|^nori\/.*)/

  filters_ignore_tags_renovate_nori_build:
    &filters_ignore_tags_renovate_nori_build
    tags:
      ignore: /.*/
    branches:
      ignore: /(^renovate-.*|^nori\/.*|^gh-pages)/

  filters_main_branch:
    &filters_main_branch
    branches:
      only:
        - main

  filters_release_build:
    &filters_release_build
    tags:
      only:
        - /^v\d+\.\d+\.\d+(?:-\w+\.\d+)?$/
    branches:
      ignore: /.*/

jobs:

  build:
    <<: *container_config_node
    steps:
      - checkout
      - *restore_cache
      - node/install-npm:
          version: "8"
      - run:
          name: Install project dependencies
          command: npm install
      - run:
          name: Run build
          command: npm run build
      - *create_cache
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - build

  test:
    <<: *container_config_node
    steps:
      - *attach_workspace
      - browser-tools/install-chrome
      - run:
          name: Check code style
          command: npm run prettier -- --list-different
      - run:
          name: Run package tests
          command: npm run test -- --runInBand
      - run:
          name: Run example app integration tests
          command: npm run test:examples
      - run:
          name: Run storybook
          command: npm run storybook:ci

  publish:
    <<: *container_config_node
    steps:
      - *attach_workspace
      - run:
          name: Set npm auth token
          command: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" >
            ${HOME}/.npmrc
      - run:
          name: Bump version
          command: npx athloi version ${CIRCLE_TAG} --filter "dotcom-*"
      - run:
          name: NPM publish
          command: |
            export DIST_TAG=$(node scripts/get-npm-dist-tag.js $CIRCLE_TAG)
            if [[ $DIST_TAG ]]; then npx athloi publish -- --access=public --tag=${DIST_TAG}; fi

  deploy:
    <<: *container_config_node
    steps:
      - *attach_workspace
      - run:
          name: Deploy Storybook
          command: npm run deploy-storybook:ci

workflows:

  version: 2

  build-test:
    jobs:
      - build:
          filters:
            <<: *filters_ignore_tags_renovate_nori_build
          name: build-v<< matrix.node-version >>
          matrix:
            parameters:
              node-version: [ "16.14", "14.19" ]
      - test:
          requires:
            - build-v<< matrix.node-version >>
          name: test-v<< matrix.node-version >>
          matrix:
            parameters:
              node-version: [ "16.14", "14.19" ]
      - deploy:
          filters:
            <<: *filters_only_main
          requires:
            - test-v<< matrix.node-version >>
          name: deploy-v<< matrix.node-version >>
          matrix:
            parameters:
              node-version: [ "16.14", "14.19" ]

  renovate-nori-build-test:
    jobs:
      - waiting-for-approval:
          type: approval
          filters:
            <<: *filters_only_renovate_nori
      - build:
          requires:
            - waiting-for-approval
          name: build-v<< matrix.node-version >>
          matrix:
            parameters:
              node-version: [ "16.14", "14.19" ]
      - test:
          requires:
            - build-v<< matrix.node-version >>
          name: test-v<< matrix.node-version >>
          matrix:
            parameters:
              node-version: [ "16.14", "14.19" ]

  build-test-publish:
    jobs:
      - build:
          filters:
            <<: *filters_release_build
          name: build-v<< matrix.node-version >>
          matrix:
            parameters:
              node-version: [ "16.14", "14.19" ]
      - test:
          filters:
            <<: *filters_release_build
          requires:
            - build-v<< matrix.node-version >>
          name: test-v<< matrix.node-version >>
          matrix:
            parameters:
              node-version: [ "16.14", "14.19" ]
      - publish:
          context: npm-publish-token
          filters:
            <<: *filters_release_build
          requires:
            - test-v16.14
