export * from './components/Types'
export * from './components/Title'
export * from './components/Favicon'
export * from './components/Description'
export * from './components/SocialMedia'
export * from './fontURLs'
export * from './defaultColors'
